### PR TITLE
fix: set `options$engine` to support quarto 1.3

### LINKED ISSUE #109: PRQL code blocks are not rendered correctly with Quarto CLI 1.3 (preview)
The `lang` option seems to be ignored.

I think a workaround is to use `engine` option instead of `lang` option here.

https://github.com/eitsupi/prqlr/blob/1ed9ca80bdcb20df4247959cd3baf584ba7f6011/R/knitr-engine.R#L22

### PR DESCRIPTION
**Pull request by eitsupi**
Fix #109

See also quarto-dev/quarto-cli#4735

### CODE REVIEW

File: R/knitr-engine.R [hunk 1]
```diff
@@ -21,6 +21,10 @@ eng_prql <- function(options) {
   # elm coincidentally provides the best syntax highlight for prql.
   options$lang <- options$lang %||% "elm"
 
+  # Workaround for Quarto CLI 1.3
+  # https://github.com/quarto-dev/quarto-cli/pull/4735
+  options$engine <- "elm"
```
Comment (cderv) [inline R/knitr-engine.R:26]: If you want to be complete in your workaround, you probably need to use 

`options$engine <- options$lang` in case a user has change the `lang` option . Otherwise it won't apply 

Don't you think ?

```suggestion
  options$lang <- options$lang %||% "elm"

  # Workaround for Quarto CLI 1.3
  # https://github.com/quarto-dev/quarto-cli/pull/4735
  options$engine <-  options$lang
```

**Review by cderv — COMMENTED** [review]
I think this is good. You just need to check that changing the option here does not have side effect with `knitr::knit_engines$get("sql")` that you use after. 

I don't think so.

File: R/knitr-engine.R (hunk 1 above)
Comment (eitsupi) [reply R/knitr-engine.R:26]: Thanks for the suggestion!
I will add a test to make sure `lang` changes are possible.

Comment (eitsupi) [reply R/knitr-engine.R:26]: It seems that the `lang` option is respected by the `knitr::knit()` function even without this change.
Is there any possibility that fixing engine to `"elm"` will cause any problems?
